/**
 * Datos de prueba del catálogo (Fase 1 — shell visual). ~26 singles de ejemplo
 * tipados como `InventoryItem` del contrato real, para que el cableado a D1 en
 * una sesión futura sea cambio de FUENTE de datos, no de tipos.
 *
 * Precios en CENTAVOS MXN (entero). Las cartas MTG llevan URL de imagen real de
 * Scryfall (ver `SCRYFALL_IMAGES`); las no-MTG quedan con `imageUrl: null` y
 * conservan el placeholder geométrico (Scryfall es MTG-only).
 */
import {
  ANCHOR_SELLER_ID,
  type Condition,
  type InventoryItem,
  type Tcg,
} from '@thepubmarket/shared'

interface Spec {
  id: string
  name: string
  tcg: Tcg
  setCode: string
  setName: string
  num: string
  rarity: string
  cond: Condition
  /** Idioma de la impresión: 'es' | 'en' | 'jp'. */
  lang: string
  foil: boolean
  /** Precio en PESOS enteros; se convierte a centavos al construir. */
  pesos: number
  qty: number
  artist: string
}

/**
 * URLs de imagen de Scryfall por id de mock (solo MTG; Scryfall es MTG-only).
 * Las 4 cartas no-MTG (Charizard, Blue-Eyes, Luffy, Elsa) no tienen entrada y
 * conservan el placeholder geométrico.
 */
const SCRYFALL_IMAGES: Record<string, string> = {
  'sol-ring':
    'https://cards.scryfall.io/normal/front/4/6/46ca0b66-a000-4483-b916-f5b89e710244.jpg?1689999818',
  ragavan:
    'https://cards.scryfall.io/normal/front/a/9/a9738cda-adb1-47fb-9f4c-ecd930228c4d.jpg?1782182183',
  counterspell:
    'https://cards.scryfall.io/normal/front/4/f/4f616706-ec97-4923-bb1e-11a69fbaa1f8.jpg?1751282477',
  bolt: 'https://cards.scryfall.io/normal/front/f/2/f29ba16f-c8fb-42fe-aabf-87089cb214a7.jpg?1673147852',
  llanowar:
    'https://cards.scryfall.io/normal/front/5/8/581b7327-3215-4a4f-b4ae-d9d4002ba882.jpg?1562736014',
  sheoldred:
    'https://cards.scryfall.io/normal/front/d/6/d67be074-cdd4-41d9-ac89-0a0456c4e4b2.jpg?1674057568',
  brainstorm:
    'https://cards.scryfall.io/normal/front/3/e/3e4e6787-af32-44f2-ac56-6f348254aa6d.jpg?1580013886',
  teferi:
    'https://cards.scryfall.io/normal/front/5/d/5d10b752-d9cb-419d-a5c4-d4ee1acb655e.jpg?1562736365',
  'fatal-push':
    'https://cards.scryfall.io/normal/front/b/5/b5e81649-9954-424c-89d1-f87d73b66047.jpg?1595869185',
  thoughtseize:
    'https://cards.scryfall.io/normal/front/b/2/b281a308-ab6b-47b6-bec7-632c9aaecede.jpg?1599706001',
  snapcaster:
    'https://cards.scryfall.io/normal/front/4/c/4cbdacc1-7a1b-4633-85f5-eb50c2bf406d.jpg?1593813139',
  birds:
    'https://cards.scryfall.io/normal/front/3/0/307d4236-1e54-43e3-83f1-063d49d16dda.jpg?1562637721',
  'wrenn-six':
    'https://cards.scryfall.io/normal/front/4/a/4a706ecf-3277-40e3-871c-4ba4ead16e20.jpg?1582053605',
  'force-of-will':
    'https://cards.scryfall.io/normal/front/e/b/ebc01ab4-d89a-4d25-bf54-6aed33772f4b.jpg?1580013954',
  'mana-crypt':
    'https://cards.scryfall.io/normal/front/4/d/4d960186-4559-4af0-bd22-63baa15f8939.jpg?1727298349',
  swords:
    'https://cards.scryfall.io/normal/front/c/c/cc9ece2f-7eda-4fc5-a562-3e16e71560e9.jpg?1623592209',
  'demonic-tutor':
    'https://cards.scryfall.io/normal/front/3/0/3009ba46-c9f8-46dc-8ffc-2aa4cef7b17c.jpg?1623779988',
  'cyclonic-rift':
    'https://cards.scryfall.io/normal/front/2/0/205c4689-8b02-4d40-9274-3c1fcafa8b82.jpg?1562783580',
  'path-to-exile':
    'https://cards.scryfall.io/normal/front/9/5/95ca89ea-1200-4bb4-ae4b-af35d3ccd35b.jpg?1781014043',
  atraxa:
    'https://cards.scryfall.io/normal/front/d/0/d0d33d52-3d28-4635-b985-51e126289259.jpg?1599707796',
  dockside:
    'https://cards.scryfall.io/normal/front/9/e/9e2e3efb-75cb-430f-b9f4-cb58f3aeb91b.jpg?1727093692',
  'mother-of-runes':
    'https://cards.scryfall.io/normal/front/a/5/a5e19147-e459-43a6-8ef0-e37968a462e3.jpg?1674141175',
}

function listing(s: Spec): InventoryItem {
  return {
    id: s.id,
    sellerId: ANCHOR_SELLER_ID,
    tcg: s.tcg,
    card: {
      scryfallId: `mock-${s.id}`,
      oracleId: `oracle-${s.id}`,
      name: s.name,
      setCode: s.setCode,
      setName: s.setName,
      collectorNumber: s.num,
      lang: s.lang,
      rarity: s.rarity,
      artist: s.artist,
      finishes: s.foil ? ['nonfoil', 'foil'] : ['nonfoil'],
      imageUrl: SCRYFALL_IMAGES[s.id] ?? null,
    },
    condition: s.cond,
    language: s.lang,
    finish: s.foil ? 'foil' : 'nonfoil',
    priceCents: s.pesos * 100,
    quantity: s.qty,
    status: 'active',
  }
}

const SPECS: Spec[] = [
  // ---- Magic: The Gathering (producto inicial) ----
  {
    id: 'sol-ring',
    name: 'Sol Ring',
    tcg: 'mtg',
    setCode: 'CMM',
    setName: 'Commander Masters',
    num: '410',
    rarity: 'Uncommon',
    cond: 'NM',
    lang: 'es',
    foil: true,
    pesos: 389,
    qty: 6,
    artist: 'Mike Bierek',
  },
  {
    id: 'ragavan',
    name: 'Ragavan, Nimble Pilferer',
    tcg: 'mtg',
    setCode: 'MH2',
    setName: 'Modern Horizons 2',
    num: '138',
    rarity: 'Mythic',
    cond: 'NM',
    lang: 'en',
    foil: true,
    pesos: 2450,
    qty: 2,
    artist: 'Simon Dominic',
  },
  {
    id: 'counterspell',
    name: 'Counterspell',
    tcg: 'mtg',
    setCode: 'DMU',
    setName: 'Dominaria United',
    num: '46',
    rarity: 'Common',
    cond: 'LP',
    lang: 'es',
    foil: false,
    pesos: 95,
    qty: 14,
    artist: 'Mark Tedin',
  },
  {
    id: 'bolt',
    name: 'Lightning Bolt',
    tcg: 'mtg',
    setCode: 'MH2',
    setName: 'Modern Horizons 2',
    num: '401',
    rarity: 'Common',
    cond: 'NM',
    lang: 'en',
    foil: false,
    pesos: 120,
    qty: 20,
    artist: 'Christopher Moeller',
  },
  {
    id: 'llanowar',
    name: 'Llanowar Elves',
    tcg: 'mtg',
    setCode: 'DMU',
    setName: 'Dominaria United',
    num: '168',
    rarity: 'Common',
    cond: 'MP',
    lang: 'es',
    foil: false,
    pesos: 35,
    qty: 9,
    artist: 'Chris Rahn',
  },
  {
    id: 'sheoldred',
    name: 'Sheoldred, the Apocalypse',
    tcg: 'mtg',
    setCode: 'DMU',
    setName: 'Dominaria United',
    num: '107',
    rarity: 'Mythic',
    cond: 'NM',
    lang: 'en',
    foil: true,
    pesos: 3200,
    qty: 0,
    artist: 'Chris Rahn',
  },
  {
    id: 'brainstorm',
    name: 'Brainstorm',
    tcg: 'mtg',
    setCode: 'DMU',
    setName: 'Dominaria United',
    num: '44',
    rarity: 'Common',
    cond: 'HP',
    lang: 'es',
    foil: false,
    pesos: 28,
    qty: 11,
    artist: 'DiTerlizzi',
  },
  {
    id: 'teferi',
    name: 'Teferi, Hero of Dominaria',
    tcg: 'mtg',
    setCode: 'DAR',
    setName: 'Dominaria',
    num: '207',
    rarity: 'Mythic',
    cond: 'NM',
    lang: 'en',
    foil: true,
    pesos: 720,
    qty: 1,
    artist: 'Chris Rallis',
  },
  {
    id: 'fatal-push',
    name: 'Fatal Push',
    tcg: 'mtg',
    setCode: 'AER',
    setName: 'Aether Revolt',
    num: '57',
    rarity: 'Uncommon',
    cond: 'NM',
    lang: 'en',
    foil: false,
    pesos: 60,
    qty: 12,
    artist: 'Liana Steinbach',
  },
  {
    id: 'thoughtseize',
    name: 'Thoughtseize',
    tcg: 'mtg',
    setCode: '2XM',
    setName: 'Double Masters',
    num: '109',
    rarity: 'Rare',
    cond: 'NM',
    lang: 'en',
    foil: false,
    pesos: 350,
    qty: 3,
    artist: 'Aleksi Briclot',
  },
  {
    id: 'snapcaster',
    name: 'Snapcaster Mage',
    tcg: 'mtg',
    setCode: 'MM3',
    setName: 'Modern Masters 2017',
    num: '51',
    rarity: 'Mythic',
    cond: 'LP',
    lang: 'en',
    foil: true,
    pesos: 480,
    qty: 2,
    artist: 'Volkan Baga',
  },
  {
    id: 'birds',
    name: 'Birds of Paradise',
    tcg: 'mtg',
    setCode: 'M12',
    setName: 'Magic 2012',
    num: '165',
    rarity: 'Rare',
    cond: 'NM',
    lang: 'es',
    foil: false,
    pesos: 180,
    qty: 8,
    artist: 'Marcelo Vignali',
  },
  {
    id: 'wrenn-six',
    name: 'Wrenn and Six',
    tcg: 'mtg',
    setCode: 'MH1',
    setName: 'Modern Horizons',
    num: '217',
    rarity: 'Mythic',
    cond: 'NM',
    lang: 'en',
    foil: true,
    pesos: 1450,
    qty: 1,
    artist: 'Yongjae Choi',
  },
  {
    id: 'force-of-will',
    name: 'Force of Will',
    tcg: 'mtg',
    setCode: 'EMA',
    setName: 'Eternal Masters',
    num: '49',
    rarity: 'Mythic',
    cond: 'LP',
    lang: 'en',
    foil: false,
    pesos: 1890,
    qty: 2,
    artist: 'Terese Nielsen',
  },
  {
    id: 'mana-crypt',
    name: 'Mana Crypt',
    tcg: 'mtg',
    setCode: '2XM',
    setName: 'Double Masters',
    num: '270',
    rarity: 'Mythic',
    cond: 'NM',
    lang: 'en',
    foil: true,
    pesos: 2100,
    qty: 0,
    artist: 'Daniel Ljunggren',
  },
  {
    id: 'swords',
    name: 'Swords to Plowshares',
    tcg: 'mtg',
    setCode: 'STA',
    setName: 'Strixhaven Mystical Archive',
    num: '20',
    rarity: 'Uncommon',
    cond: 'NM',
    lang: 'es',
    foil: false,
    pesos: 75,
    qty: 15,
    artist: 'Ron Spencer',
  },
  {
    id: 'demonic-tutor',
    name: 'Demonic Tutor',
    tcg: 'mtg',
    setCode: 'STA',
    setName: 'Strixhaven Mystical Archive',
    num: '91',
    rarity: 'Rare',
    cond: 'NM',
    lang: 'en',
    foil: true,
    pesos: 240,
    qty: 4,
    artist: 'Daarken',
  },
  {
    id: 'cyclonic-rift',
    name: 'Cyclonic Rift',
    tcg: 'mtg',
    setCode: '2X2',
    setName: 'Double Masters 2022',
    num: '51',
    rarity: 'Rare',
    cond: 'NM',
    lang: 'es',
    foil: false,
    pesos: 320,
    qty: 6,
    artist: 'Tommy Arnold',
  },
  {
    id: 'path-to-exile',
    name: 'Path to Exile',
    tcg: 'mtg',
    setCode: 'MM2',
    setName: 'Modern Masters 2015',
    num: '25',
    rarity: 'Uncommon',
    cond: 'NM',
    lang: 'es',
    foil: false,
    pesos: 90,
    qty: 11,
    artist: 'Slawomir Maniak',
  },
  {
    id: 'atraxa',
    name: "Atraxa, Praetors' Voice",
    tcg: 'mtg',
    setCode: 'C16',
    setName: 'Commander 2016',
    num: '28',
    rarity: 'Mythic',
    cond: 'NM',
    lang: 'en',
    foil: false,
    pesos: 560,
    qty: 3,
    artist: 'Victor Adame Minguez',
  },
  {
    id: 'dockside',
    name: 'Dockside Extortionist',
    tcg: 'mtg',
    setCode: 'C19',
    setName: 'Commander 2019',
    num: '13',
    rarity: 'Rare',
    cond: 'LP',
    lang: 'en',
    foil: false,
    pesos: 980,
    qty: 2,
    artist: 'Mathias Kollros',
  },
  {
    id: 'mother-of-runes',
    name: 'Mother of Runes',
    tcg: 'mtg',
    setCode: 'DMR',
    setName: 'Dominaria Remastered',
    num: '24',
    rarity: 'Rare',
    cond: 'NM',
    lang: 'es',
    foil: true,
    pesos: 210,
    qty: 5,
    artist: 'Anna Steinbauer',
  },

  // ---- Otros TCG (fidelidad al diseño; lanzamiento real es MTG-first) ----
  {
    id: 'charizard',
    name: 'Charizard ex',
    tcg: 'pokemon',
    setCode: 'MEW',
    setName: '151',
    num: '199',
    rarity: 'Special',
    cond: 'NM',
    lang: 'es',
    foil: true,
    pesos: 1890,
    qty: 3,
    artist: 'PLANETA',
  },
  {
    id: 'blueeyes',
    name: 'Blue-Eyes White Dragon',
    tcg: 'yugioh',
    setCode: 'LOB',
    setName: 'Legend of Blue Eyes',
    num: '001',
    rarity: 'Ultra',
    cond: 'LP',
    lang: 'en',
    foil: false,
    pesos: 640,
    qty: 4,
    artist: 'Kazuki Takahashi',
  },
  {
    id: 'luffy',
    name: 'Monkey D. Luffy',
    tcg: 'onepiece',
    setCode: 'OP-01',
    setName: 'Romance Dawn',
    num: '120',
    rarity: 'Leader',
    cond: 'NM',
    lang: 'es',
    foil: true,
    pesos: 980,
    qty: 5,
    artist: 'Eiichiro Oda',
  },
  {
    id: 'elsa',
    name: 'Elsa — Snow Queen',
    tcg: 'lorcana',
    setCode: 'TFC',
    setName: 'The First Chapter',
    num: '042',
    rarity: 'Legendary',
    cond: 'NM',
    lang: 'en',
    foil: false,
    pesos: 410,
    qty: 7,
    artist: 'Ravensburger',
  },
]

/** Inventario mock completo, en el mismo formato que devolverá la API real. */
export const MOCK_LISTINGS: InventoryItem[] = SPECS.map(listing)
