/**
 * Datos de prueba del catálogo (Fase 1 — shell visual). ~26 singles de ejemplo
 * tipados como `InventoryItem` del contrato real, para que el cableado a D1 en
 * una sesión futura sea cambio de FUENTE de datos, no de tipos.
 *
 * Precios en CENTAVOS MXN (entero). Las imágenes son null a propósito: el
 * `ProductCard` renderiza el placeholder geométrico del diseño (arte real llega
 * con la integración de Scryfall/R2).
 */
import {
  ANCHOR_SELLER_ID,
  type Condition,
  type InventoryItem,
  type Tcg,
} from '@thepubmarket/shared'

interface Spec {
  id: string
  name: string
  tcg: Tcg
  setCode: string
  setName: string
  num: string
  rarity: string
  cond: Condition
  /** Idioma de la impresión: 'es' | 'en' | 'jp'. */
  lang: string
  foil: boolean
  /** Precio en PESOS enteros; se convierte a centavos al construir. */
  pesos: number
  qty: number
  artist: string
}

function listing(s: Spec): InventoryItem {
  return {
    id: s.id,
    sellerId: ANCHOR_SELLER_ID,
    tcg: s.tcg,
    card: {
      scryfallId: `mock-${s.id}`,
      oracleId: `oracle-${s.id}`,
      name: s.name,
      setCode: s.setCode,
      setName: s.setName,
      collectorNumber: s.num,
      lang: s.lang,
      rarity: s.rarity,
      artist: s.artist,
      finishes: s.foil ? ['nonfoil', 'foil'] : ['nonfoil'],
      imageUrl: null,
    },
    condition: s.cond,
    language: s.lang,
    finish: s.foil ? 'foil' : 'nonfoil',
    priceCents: s.pesos * 100,
    quantity: s.qty,
    status: 'active',
  }
}

const SPECS: Spec[] = [
  // ---- Magic: The Gathering (producto inicial) ----
  {
    id: 'sol-ring',
    name: 'Sol Ring',
    tcg: 'mtg',
    setCode: 'CMM',
    setName: 'Commander Masters',
    num: '410',
    rarity: 'Uncommon',
    cond: 'NM',
    lang: 'es',
    foil: true,
    pesos: 389,
    qty: 6,
    artist: 'Mike Bierek',
  },
  {
    id: 'ragavan',
    name: 'Ragavan, Nimble Pilferer',
    tcg: 'mtg',
    setCode: 'MH2',
    setName: 'Modern Horizons 2',
    num: '138',
    rarity: 'Mythic',
    cond: 'NM',
    lang: 'en',
    foil: true,
    pesos: 2450,
    qty: 2,
    artist: 'Simon Dominic',
  },
  {
    id: 'counterspell',
    name: 'Counterspell',
    tcg: 'mtg',
    setCode: 'DMU',
    setName: 'Dominaria United',
    num: '46',
    rarity: 'Common',
    cond: 'LP',
    lang: 'es',
    foil: false,
    pesos: 95,
    qty: 14,
    artist: 'Mark Tedin',
  },
  {
    id: 'bolt',
    name: 'Lightning Bolt',
    tcg: 'mtg',
    setCode: 'MH2',
    setName: 'Modern Horizons 2',
    num: '401',
    rarity: 'Common',
    cond: 'NM',
    lang: 'en',
    foil: false,
    pesos: 120,
    qty: 20,
    artist: 'Christopher Moeller',
  },
  {
    id: 'llanowar',
    name: 'Llanowar Elves',
    tcg: 'mtg',
    setCode: 'DMU',
    setName: 'Dominaria United',
    num: '168',
    rarity: 'Common',
    cond: 'MP',
    lang: 'es',
    foil: false,
    pesos: 35,
    qty: 9,
    artist: 'Chris Rahn',
  },
  {
    id: 'sheoldred',
    name: 'Sheoldred, the Apocalypse',
    tcg: 'mtg',
    setCode: 'DMU',
    setName: 'Dominaria United',
    num: '107',
    rarity: 'Mythic',
    cond: 'NM',
    lang: 'en',
    foil: true,
    pesos: 3200,
    qty: 0,
    artist: 'Chris Rahn',
  },
  {
    id: 'brainstorm',
    name: 'Brainstorm',
    tcg: 'mtg',
    setCode: 'DMU',
    setName: 'Dominaria United',
    num: '44',
    rarity: 'Common',
    cond: 'HP',
    lang: 'es',
    foil: false,
    pesos: 28,
    qty: 11,
    artist: 'DiTerlizzi',
  },
  {
    id: 'teferi',
    name: 'Teferi, Hero of Dominaria',
    tcg: 'mtg',
    setCode: 'DAR',
    setName: 'Dominaria',
    num: '207',
    rarity: 'Mythic',
    cond: 'NM',
    lang: 'en',
    foil: true,
    pesos: 720,
    qty: 1,
    artist: 'Chris Rallis',
  },
  {
    id: 'fatal-push',
    name: 'Fatal Push',
    tcg: 'mtg',
    setCode: 'AER',
    setName: 'Aether Revolt',
    num: '57',
    rarity: 'Uncommon',
    cond: 'NM',
    lang: 'en',
    foil: false,
    pesos: 60,
    qty: 12,
    artist: 'Liana Steinbach',
  },
  {
    id: 'thoughtseize',
    name: 'Thoughtseize',
    tcg: 'mtg',
    setCode: '2XM',
    setName: 'Double Masters',
    num: '109',
    rarity: 'Rare',
    cond: 'NM',
    lang: 'en',
    foil: false,
    pesos: 350,
    qty: 3,
    artist: 'Aleksi Briclot',
  },
  {
    id: 'snapcaster',
    name: 'Snapcaster Mage',
    tcg: 'mtg',
    setCode: 'MM3',
    setName: 'Modern Masters 2017',
    num: '51',
    rarity: 'Mythic',
    cond: 'LP',
    lang: 'en',
    foil: true,
    pesos: 480,
    qty: 2,
    artist: 'Volkan Baga',
  },
  {
    id: 'birds',
    name: 'Birds of Paradise',
    tcg: 'mtg',
    setCode: 'M12',
    setName: 'Magic 2012',
    num: '165',
    rarity: 'Rare',
    cond: 'NM',
    lang: 'es',
    foil: false,
    pesos: 180,
    qty: 8,
    artist: 'Marcelo Vignali',
  },
  {
    id: 'wrenn-six',
    name: 'Wrenn and Six',
    tcg: 'mtg',
    setCode: 'MH1',
    setName: 'Modern Horizons',
    num: '217',
    rarity: 'Mythic',
    cond: 'NM',
    lang: 'en',
    foil: true,
    pesos: 1450,
    qty: 1,
    artist: 'Yongjae Choi',
  },
  {
    id: 'force-of-will',
    name: 'Force of Will',
    tcg: 'mtg',
    setCode: 'EMA',
    setName: 'Eternal Masters',
    num: '49',
    rarity: 'Mythic',
    cond: 'LP',
    lang: 'en',
    foil: false,
    pesos: 1890,
    qty: 2,
    artist: 'Terese Nielsen',
  },
  {
    id: 'mana-crypt',
    name: 'Mana Crypt',
    tcg: 'mtg',
    setCode: '2XM',
    setName: 'Double Masters',
    num: '270',
    rarity: 'Mythic',
    cond: 'NM',
    lang: 'en',
    foil: true,
    pesos: 2100,
    qty: 0,
    artist: 'Daniel Ljunggren',
  },
  {
    id: 'swords',
    name: 'Swords to Plowshares',
    tcg: 'mtg',
    setCode: 'STA',
    setName: 'Strixhaven Mystical Archive',
    num: '20',
    rarity: 'Uncommon',
    cond: 'NM',
    lang: 'es',
    foil: false,
    pesos: 75,
    qty: 15,
    artist: 'Ron Spencer',
  },
  {
    id: 'demonic-tutor',
    name: 'Demonic Tutor',
    tcg: 'mtg',
    setCode: 'STA',
    setName: 'Strixhaven Mystical Archive',
    num: '91',
    rarity: 'Rare',
    cond: 'NM',
    lang: 'en',
    foil: true,
    pesos: 240,
    qty: 4,
    artist: 'Daarken',
  },
  {
    id: 'cyclonic-rift',
    name: 'Cyclonic Rift',
    tcg: 'mtg',
    setCode: '2X2',
    setName: 'Double Masters 2022',
    num: '51',
    rarity: 'Rare',
    cond: 'NM',
    lang: 'es',
    foil: false,
    pesos: 320,
    qty: 6,
    artist: 'Tommy Arnold',
  },
  {
    id: 'path-to-exile',
    name: 'Path to Exile',
    tcg: 'mtg',
    setCode: 'MM2',
    setName: 'Modern Masters 2015',
    num: '25',
    rarity: 'Uncommon',
    cond: 'NM',
    lang: 'es',
    foil: false,
    pesos: 90,
    qty: 11,
    artist: 'Slawomir Maniak',
  },
  {
    id: 'atraxa',
    name: "Atraxa, Praetors' Voice",
    tcg: 'mtg',
    setCode: 'C16',
    setName: 'Commander 2016',
    num: '28',
    rarity: 'Mythic',
    cond: 'NM',
    lang: 'en',
    foil: false,
    pesos: 560,
    qty: 3,
    artist: 'Victor Adame Minguez',
  },
  {
    id: 'dockside',
    name: 'Dockside Extortionist',
    tcg: 'mtg',
    setCode: 'C19',
    setName: 'Commander 2019',
    num: '13',
    rarity: 'Rare',
    cond: 'LP',
    lang: 'en',
    foil: false,
    pesos: 980,
    qty: 2,
    artist: 'Mathias Kollros',
  },
  {
    id: 'mother-of-runes',
    name: 'Mother of Runes',
    tcg: 'mtg',
    setCode: 'DMR',
    setName: 'Dominaria Remastered',
    num: '24',
    rarity: 'Rare',
    cond: 'NM',
    lang: 'es',
    foil: true,
    pesos: 210,
    qty: 5,
    artist: 'Anna Steinbauer',
  },

  // ---- Otros TCG (fidelidad al diseño; lanzamiento real es MTG-first) ----
  {
    id: 'charizard',
    name: 'Charizard ex',
    tcg: 'pokemon',
    setCode: 'MEW',
    setName: '151',
    num: '199',
    rarity: 'Special',
    cond: 'NM',
    lang: 'es',
    foil: true,
    pesos: 1890,
    qty: 3,
    artist: 'PLANETA',
  },
  {
    id: 'blueeyes',
    name: 'Blue-Eyes White Dragon',
    tcg: 'yugioh',
    setCode: 'LOB',
    setName: 'Legend of Blue Eyes',
    num: '001',
    rarity: 'Ultra',
    cond: 'LP',
    lang: 'en',
    foil: false,
    pesos: 640,
    qty: 4,
    artist: 'Kazuki Takahashi',
  },
  {
    id: 'luffy',
    name: 'Monkey D. Luffy',
    tcg: 'onepiece',
    setCode: 'OP-01',
    setName: 'Romance Dawn',
    num: '120',
    rarity: 'Leader',
    cond: 'NM',
    lang: 'es',
    foil: true,
    pesos: 980,
    qty: 5,
    artist: 'Eiichiro Oda',
  },
  {
    id: 'elsa',
    name: 'Elsa — Snow Queen',
    tcg: 'lorcana',
    setCode: 'TFC',
    setName: 'The First Chapter',
    num: '042',
    rarity: 'Legendary',
    cond: 'NM',
    lang: 'en',
    foil: false,
    pesos: 410,
    qty: 7,
    artist: 'Ravensburger',
  },
]

/** Inventario mock completo, en el mismo formato que devolverá la API real. */
export const MOCK_LISTINGS: InventoryItem[] = SPECS.map(listing)
